spring:
  datasource:
    url: jdbc:p6spy:mariadb://localhost:3306/app_db
    username: user
    password: pass
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    hibernate:
      ddl-auto: create-only

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: off
    p6spy: off
    com.demo.demo1racecondition: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger - %msg%n"
  file:
    name: logs/app.log          # 로그 파일 경로
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30