spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/app_db
    username: user
    password: pass
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    p6spy: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger - %msg%n"
